// <auto-generated />
using System;
using DndApp.Inventory.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DndApp.Inventory.Data.Migrations
{
    [DbContext(typeof(InventoryDbContext))]
    partial class InventoryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DndApp.Inventory.Data.Entities.InventoryAdjustment", b =>
                {
                    b.Property<Guid>("AdjustmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("DeltaQuantity")
                        .HasColumnType("numeric(18,3)");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("LotId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("ReferenceId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReferenceType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("StorageLocationId")
                        .HasColumnType("uuid");

                    b.Property<int>("WorldDay")
                        .HasColumnType("integer");

                    b.HasKey("AdjustmentId");

                    b.HasIndex("CampaignId");

                    b.HasIndex("ItemId");

                    b.HasIndex("LotId");

                    b.HasIndex("StorageLocationId");

                    b.HasIndex("CampaignId", "WorldDay", "CreatedAt");

                    b.ToTable("InventoryAdjustments", (string)null);
                });

            modelBuilder.Entity("DndApp.Inventory.Data.Entities.InventoryLot", b =>
                {
                    b.Property<Guid>("LotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AcquiredWorldDay")
                        .HasColumnType("integer");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal>("QuantityOnHand")
                        .HasColumnType("numeric(18,3)");

                    b.Property<string>("Source")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("StorageLocationId")
                        .HasColumnType("uuid");

                    b.Property<long>("UnitCostMinor")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("LotId");

                    b.HasIndex("CampaignId");

                    b.HasIndex("ItemId");

                    b.HasIndex("StorageLocationId");

                    b.HasIndex("CampaignId", "ItemId", "StorageLocationId", "AcquiredWorldDay", "CreatedAt");

                    b.ToTable("InventoryLots", null, t =>
                        {
                            t.HasCheckConstraint("CK_InventoryLots_QuantityOnHand_NonNegative", "\"QuantityOnHand\" >= 0");

                            t.HasCheckConstraint("CK_InventoryLots_UnitCostMinor_NonNegative", "\"UnitCostMinor\" >= 0");
                        });
                });

            modelBuilder.Entity("DndApp.Inventory.Data.Entities.ProcessedEvent", b =>
                {
                    b.Property<Guid>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("EventId");

                    b.ToTable("ProcessedEvents", (string)null);
                });

            modelBuilder.Entity("DndApp.Inventory.Data.Entities.StorageLocation", b =>
                {
                    b.Property<Guid>("StorageLocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid?>("PlaceId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("StorageLocationId");

                    b.HasIndex("CampaignId");

                    b.HasIndex("PlaceId");

                    b.HasIndex("CampaignId", "Name")
                        .IsUnique();

                    b.ToTable("StorageLocations", (string)null);
                });

            modelBuilder.Entity("DndApp.Inventory.Data.Entities.InventoryAdjustment", b =>
                {
                    b.HasOne("DndApp.Inventory.Data.Entities.InventoryLot", "Lot")
                        .WithMany("Adjustments")
                        .HasForeignKey("LotId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DndApp.Inventory.Data.Entities.StorageLocation", "StorageLocation")
                        .WithMany("Adjustments")
                        .HasForeignKey("StorageLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Lot");

                    b.Navigation("StorageLocation");
                });

            modelBuilder.Entity("DndApp.Inventory.Data.Entities.InventoryLot", b =>
                {
                    b.HasOne("DndApp.Inventory.Data.Entities.StorageLocation", "StorageLocation")
                        .WithMany("Lots")
                        .HasForeignKey("StorageLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("StorageLocation");
                });

            modelBuilder.Entity("DndApp.Inventory.Data.Entities.InventoryLot", b =>
                {
                    b.Navigation("Adjustments");
                });

            modelBuilder.Entity("DndApp.Inventory.Data.Entities.StorageLocation", b =>
                {
                    b.Navigation("Adjustments");

                    b.Navigation("Lots");
                });
#pragma warning restore 612, 618
        }
    }
}
