// <auto-generated />
using System;
using DndApp.Campaign.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DndApp.Campaign.Data.Migrations
{
    [DbContext(typeof(CampaignDbContext))]
    partial class CampaignDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DndApp.Campaign.Data.Entities.CalendarConfig", b =>
                {
                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid");

                    b.Property<string>("MonthsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("WeekLength")
                        .HasColumnType("integer");

                    b.HasKey("CampaignId");

                    b.ToTable("CalendarConfig", (string)null);
                });

            modelBuilder.Entity("DndApp.Campaign.Data.Entities.Campaign", b =>
                {
                    b.Property<Guid>("CampaignId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("CampaignId");

                    b.HasIndex("CreatedByUserId");

                    b.ToTable("Campaigns", (string)null);
                });

            modelBuilder.Entity("DndApp.Campaign.Data.Entities.CurrencyConfig", b =>
                {
                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("DenominationsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("MajorUnitName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("MinorUnitName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("CampaignId");

                    b.ToTable("CurrencyConfig", (string)null);
                });

            modelBuilder.Entity("DndApp.Campaign.Data.Entities.NpcCustomer", b =>
                {
                    b.Property<Guid>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("TagsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("Tags");

                    b.HasKey("CustomerId");

                    b.HasIndex("CampaignId");

                    b.HasIndex("CampaignId", "Name");

                    b.ToTable("NpcCustomers", (string)null);
                });

            modelBuilder.Entity("DndApp.Campaign.Data.Entities.Place", b =>
                {
                    b.Property<Guid>("PlaceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("PlaceId");

                    b.HasIndex("CampaignId");

                    b.HasIndex("CampaignId", "Name");

                    b.ToTable("Places", (string)null);
                });

            modelBuilder.Entity("DndApp.Campaign.Data.Entities.CalendarConfig", b =>
                {
                    b.HasOne("DndApp.Campaign.Data.Entities.Campaign", "Campaign")
                        .WithOne("CalendarConfig")
                        .HasForeignKey("DndApp.Campaign.Data.Entities.CalendarConfig", "CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("DndApp.Campaign.Data.Entities.CurrencyConfig", b =>
                {
                    b.HasOne("DndApp.Campaign.Data.Entities.Campaign", "Campaign")
                        .WithOne("CurrencyConfig")
                        .HasForeignKey("DndApp.Campaign.Data.Entities.CurrencyConfig", "CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("DndApp.Campaign.Data.Entities.NpcCustomer", b =>
                {
                    b.HasOne("DndApp.Campaign.Data.Entities.Campaign", "Campaign")
                        .WithMany("NpcCustomers")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("DndApp.Campaign.Data.Entities.Place", b =>
                {
                    b.HasOne("DndApp.Campaign.Data.Entities.Campaign", "Campaign")
                        .WithMany("Places")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("DndApp.Campaign.Data.Entities.Campaign", b =>
                {
                    b.Navigation("CalendarConfig");

                    b.Navigation("CurrencyConfig");

                    b.Navigation("NpcCustomers");

                    b.Navigation("Places");
                });
#pragma warning restore 612, 618
        }
    }
}
